# Uncomment the next line to define a global platform for your project
# platform :ios, '14.4'

target 'TortyMozyrApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Analytics'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'

pod 'SnapKit', '~> 5.0.0'

end
